e_commerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('market/', include('market.urls')),
    path('user/', include('user.urls')),
]
# Static files URL Patterns
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/urls.py
from django.urls import path
from . import views

app_name = 'market'
urlpatterns = [
    path('', views.index, name='home'),
    path('product/<str:prod_key>/', views.product, name='product'),
    path('products/', views.products, name='products' ),
]

urlpatterns += [
    path('cart/', views.cart, name='cart'),
]

user/urls.py
from django.urls import path
from .views import register, login_user, dashboard, log_out


app_name = 'user'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login_user, name='login' ),
    path('logout/', log_out, name='logout'),
]

urlpatterns += [
    path('dashboard/', dashboard, name='dashboard' ),
]

market/models.py
from django.contrib.auth.models import User
from django.db import models
from user.models import Customer


class Category(models.Model):
  """Contains Every Category of Items Available"""
  name = models.CharField(max_length=200, null=True,)

  def __str__(self):
    return self.name

  class Meta:
    verbose_name_plural = 'Categories'


class Item(models.Model):
  """Contains all The Available Items"""
  name = models.CharField(max_length=200, null=True)
  price = models.CharField(max_length=200, null=True)
  category  = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL)
  item_img = models.ImageField(upload_to = "images/")
  description = models.CharField(max_length=200, null=True)
  date_created = models.DateTimeField(auto_now_add=True, null=True)
  
  def __str__(self):
    return self.name
  class Meta:
    verbose_name_plural = 'Items'


class Size(models.Model):
  """Contains Every Size Available"""
  size_name = models.CharField(max_length=200, null=True,)

  def __str__(self):
    return self.name

  class Meta:
    verbose_name_plural = 'Sizes'

class Cart(models.Model):
  #TODO: Complete it later
  """Contains all The User's selected Items"""
  name = models.CharField(max_length=200, null=True)
  price = models.CharField(max_length=200, null=True)
  size = models.ForeignKey(Size, null=True, on_delete=models.SET_NULL)
  item_img = models.ImageField(upload_to = "images/")
  date_added = models.DateTimeField(auto_now_add=True, null=True)
  
  def __str__(self):
    return self.name
  class Meta:
    verbose_name_plural = 'Carts'


class Order(models.Model):
  STATUS = ("Pending", "Delivered")
    
  customer = models.ForeignKey(Customer, null=True, on_delete=models.SET_NULL)
  item = models.ForeignKey(Item, null=True, on_delete=models.SET_NULL)
  date_created = models.DateTimeField(auto_now_add=True, null=True)
  status = models.CharField(max_length=200, null=True)
  
  def __str__(self):
    return self.item.name

  class Meta:
    verbose_name_plural = 'Orders'

user/models.py
from django.db import models
from django.contrib.auth.models import User

class Customer(models.Model):
  user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
  name = models.CharField(max_length=200, null=True)
  phone = models.CharField(max_length=200, null=True)
  email = models.CharField(max_length=200, null=True)
  profile_pic = models.ImageField(default="images/custom/person.svg", null=True, blank=True, upload_to = "images/upload/profiles/")
  date_created = models.DateTimeField(auto_now_add=True, null=True)


  def __str__(self):
    return self.name
    
  class Meta:
    verbose_name_plural = 'Customers'
  

market/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import Item,Order
from django import forms

class ItemForm(ModelForm):
  class Meta:
    model = Item
    fields ='__all__'


  
class OrderForm(ModelForm):
  
  class Meta:
    model = Order
    fields = '__all__'
    exclude = ['status']
    
  
    

user/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import Customer


class CustomerForm(ModelForm):
  class Meta:
    model = Customer
    fields ='__all__'
    exclude = ['user']
  
class CreateUserForm(UserCreationForm):
  class Meta:
    model = User
    fields = ['username', 'email', 'password1', 'password2',]

market/views.py
from django.shortcuts import render
from .models import Item
from.forms import ItemForm

def index(request):
    all_items = Item.objects.all()
  
    context ={'items':all_items,}
    return render(request, 'market/index.html', context)


def product(request: str, prod_id: str):
    context = {
        "prod_id":prod_id,
    }
    return render(request, 'market/product.html', context)


def products(request):
    all_items = Item.objects.all()
  
    context ={
        'items':all_items,
    }
    return render(request, 'market/products.html', **context)

def cart(request):
    context = {}
    return render(request, 'market/cart.html', context)

user/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from django.contrib.auth.models import Group
from django.contrib import messages
from .forms import CustomerForm, CreateUserForm

from .decorators import unauthenticated_user, allowed_users
from django.contrib import messages


# Logs a user in
@unauthenticated_user
def login_user(request):
  if request.method =='POST':
    username = request.POST.get('username')
    password = request.POST.get('password')
      
    print(username)  
    user = authenticate(request, username=username, password=password)
    print(user)
      
    if user is not None:
      login(request, user)
      print(username, 'logged in')
      return redirect('market:home')
      
    else: messages.error(request, 'Account not Registered')
  
  return render(request, 'user/login.html')

#Logout
@login_required(login_url='user:login')
def log_out(request):
  logout(request)
  print(request.user.username, 'logged out')
  return render(request,'market/index.html')

# Registers a new user
@unauthenticated_user
def register(request):
  form = CreateUserForm()
    
  if request.method=='POST':
    form = CreateUserForm(request.POST)
    if form.is_valid():
      user = form.save()
      username = form.cleaned_data.get('username')
      
      
      messages.success(request," Account was Created for "+username)
      return redirect('user:login')
    else:
      messages.error(request, 'Incorrect credentials')
        
  context = {'form':form}
  return render(request,'user/register.html', context)

@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['Customer','Admin'])
def dashboard(request):
    user = request.user
  
    context = {}
    return render(request, 'user/dashboard.html', context)

market/templates/market/base.html
{% load static %}
{% load humanize %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>{% block title %}{% endblock title %}</title>
    
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap/media-query.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap/navbar-top.css' %}" rel="stylesheet">
    <style>
      body{
        background-color: rgba(0, 0, 0, .85);
      }
    </style>
  </head>
  <body style="background-color:#212529;">

    {% block navbar %}
      {% include 'market/navbar.html' %}
    {% endblock navbar %}

    {% block content %}{% endblock content%}      

    {% block footer %}
      {% include 'market/footer.html' %}
    {% endblock footer %}

</body>
<script src="{% static 'js/bootstrap/bootstrap.bundle.min.js' %}"></script>
</html>

market/templates/market/carousel.html
{% load static %}


<!-- Custom styles for this template -->
<link href="{% static 'css/bootstrap/carousel.css' %}" rel="stylesheet">

<main>

  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'images/t-shirt.jpg'%}" alt="empty" width="100%" height="100%">

        <div class="container">
          <div class="carousel-caption text-start">
            <h1>Example headline.</h1>
            <p style="color:black ;">Some representative placeholder content for the first slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Sign up today</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/t-shirt.jpg'%}" alt="empty" width="100%" height="100%">

        <div class="container">
          <div class="carousel-caption">
            <h1>Another example headline.</h1>
            <p>Some representative placeholder content for the second slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%"aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><img src="{% static 'images/t-shirt.jpg'%}" alt="empty" width="100%" height="100%">
</svg>

        <div class="container">
          <div class="carousel-caption text-end">
            <h1>One more for good measure.</h1>
            <p>Some representative placeholder content for the third slide of this carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Browse gallery</a></p>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

market/templates/market/cart.html
{% extends 'user/dashboard.html'%}
{% load static%}


{% block dashboard_center %}

<link href="{% static 'css/font_awesome/all.css'%}" rel="stylesheet">
<section class="h-100" style="background-color: #eee;">
  <div class="container h-100 py-5">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-10">

        <div class="d-flex justify-content-between align-items-center mb-4">
          <h3 class="fw-normal mb-0 text-black">Shopping Cart</h3>

          <a href="" style="text-decoration:none;"> <h3 class="fw-normal mb-0 text-black">Clear</h3></a>
          <div>
            <p class="mb-0"><span class="text-muted">Sort by:</span> <a href="#!" class="text-body">price <i
                  class="fas fa-angle-down mt-1"></i></a></p>
          </div>
        </div>

        <div class="card rounded-3 mb-4">
          <div class="card-body p-4">
            <div class="row d-flex justify-content-between align-items-center">
              <div class="col-md-2 col-lg-2 col-xl-2">
                <img
                  src="{% static 'images/t-shirt.jpg'%}"
                  class="img-fluid rounded-3" alt="Cotton T-shirt">
              </div>
              <div class="col-md-3 col-lg-3 col-xl-3">
                <p class="lead fw-normal mb-2">Basic T-shirt</p>
                <p><span class="text-muted">Size: </span>M <span class="text-muted">Color: </span>Grey</p>
              </div>
              <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                <button class="btn btn-link px-2"
                  onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                  <i class="fas fa-minus"></i>
                </button>

                <input id="form1" min="0" name="quantity" value="2" type="number"
                  class="form-control form-control-sm" />

                <button class="btn btn-link px-2"
                  onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                  <i class="fas fa-plus"></i>
                </button>
              </div>
              <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                <h5 class="mb-0">$499.00</h5>
              </div>
              <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                <a href="#!" class="text-danger"><i class="fas fa-trash fa-lg"></i></a>
              </div>
            </div>
          </div>
        </div>

        <div class="card rounded-3 mb-4">
          <div class="card-body p-4">
            <div class="row d-flex justify-content-between align-items-center">
              <div class="col-md-2 col-lg-2 col-xl-2">
                <img
                  src="{% static 'images/t-shirt.jpg'%}"
                  class="img-fluid rounded-3" alt="Cotton T-shirt">
              </div>
              <div class="col-md-3 col-lg-3 col-xl-3">
                <p class="lead fw-normal mb-2">Basic T-shirt</p>
                <p><span class="text-muted">Size: </span>M <span class="text-muted">Color: </span>Grey</p>
              </div>
              <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                <button class="btn btn-link px-2"
                  onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                  <i class="fas fa-minus"></i>
                </button>

                <input id="form1" min="0" name="quantity" value="2" type="number"
                  class="form-control form-control-sm" />

                <button class="btn btn-link px-2"
                  onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                  <i class="fas fa-plus"></i>
                </button>
              </div>
              <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                <h5 class="mb-0">$499.00</h5>
              </div>
              <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                <a href="#!" class="text-danger"><i class="fas fa-trash fa-lg"></i></a>
              </div>
            </div>
          </div>
        </div>

        <div class="card rounded-3 mb-4">
          <div class="card-body p-4">
            <div class="row d-flex justify-content-between align-items-center">
              <div class="col-md-2 col-lg-2 col-xl-2">
                <img
                  src="{% static 'images/t-shirt.jpg'%}"
                  class="img-fluid rounded-3" alt="Cotton T-shirt">
              </div>
              <div class="col-md-3 col-lg-3 col-xl-3">
                <p class="lead fw-normal mb-2">Basic T-shirt</p>
                <p><span class="text-muted">Size: </span>M <span class="text-muted">Color: </span>Grey</p>
              </div>
              <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                <button class="btn btn-link px-2"
                  onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                  <i class="fas fa-minus"></i>
                </button>

                <input id="form1" min="0" name="quantity" value="2" type="number"
                  class="form-control form-control-sm" />

                <button class="btn btn-link px-2"
                  onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                  <i class="fas fa-plus"></i>
                </button>
              </div>
              <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                <h5 class="mb-0">$499.00</h5>
              </div>
              <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                <a href="#!" class="text-danger"><i class="fas fa-trash fa-lg"></i></a>
              </div>
            </div>
          </div>
        </div>

        <div class="card rounded-3 mb-4">
          <div class="card-body p-4">
            <div class="row d-flex justify-content-between align-items-center">
              <div class="col-md-2 col-lg-2 col-xl-2">
                <img
                  src="{% static 'images/t-shirt.jpg'%}"
                  class="img-fluid rounded-3" alt="Cotton T-shirt">
              </div>
              <div class="col-md-3 col-lg-3 col-xl-3">
                <p class="lead fw-normal mb-2">Basic T-shirt</p>
                <p><span class="text-muted">Size: </span>M <span class="text-muted">Color: </span>Grey</p>
              </div>
              <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                <button class="btn btn-link px-2"
                  onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                  <i class="fas fa-minus"></i>
                </button>

                <input id="form1" min="0" name="quantity" value="2" type="number"
                  class="form-control form-control-sm" />

                <button class="btn btn-link px-2"
                  onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                  <i class="fas fa-plus"></i>
                </button>
              </div>
              <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                <h5 class="mb-0">$499.00</h5>
              </div>
              <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                <a href="#!" class="text-danger"><i class="fas fa-trash fa-lg"></i></a>
              </div>
            </div>
          </div>
        </div>

        <div class="card mb-4">
          <div class="card-body p-4 d-flex flex-row">
            <div class="form-outline flex-fill">
              <input type="text" id="form1" class="form-control form-control-lg" />
              <label class="form-label" for="form1">Discound code</label>
            </div>
            <button type="button" class="btn btn-outline-warning btn-lg ms-3">Apply</button>
          </div>
        </div>

        <div class="card">
          <div class="card-body">

            <a href="{% url 'market:home' %}" class="text-body">
              <button type="button" class="btn btn-warning btn-block btn-lg ">
                <i class="fas fa-long-arrow-alt-left me-2"></i>
                  Back to shop
              </button>
            </a>

            <button type="button" class="btn btn-warning btn-block btn-lg">Proceed to Pay</button>
          </div>
        </div>

      </div>
    </div>
  </div>
</section>
{% endblock dashboard_center %}

market/templates/market/index.html
{% extends 'market/base.html' %}
{% load static %}


{% block title %} Buy and Sell {% endblock title %}

{% block content%}
    {% include 'market/carousel.html' %}
    {% include 'market/products.html' %}
{% endblock content%}

market/templates/market/navbar.html
{% load static %}
<link href="{% static 'css/font_awesome/all.css'%}" rel="stylesheet">
<link href="{% static 'css/custom/cart-font.css'%}" rel="stylesheet">

<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-0 mt-0">
  <div class="container-fluid">
    <h3><a class="nav-link active" aria-current="page" href="{% url 'market:home' %}" style="color:goldenrod ;">Nicks Shorts</a></h3> 
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-bs-toggle="dropdown" aria-expanded="false">Category</a>
            <ul class="dropdown-menu" aria-labelledby="dropdown03">
              <li><a class="dropdown-item" href="#">Black</a></li>
              <li><a class="dropdown-item" href="#">Brown</a></li>
              <li><a class="dropdown-item" href="#">White</a></li>
            </ul>
        </li>

        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:dashboard'%}">My Dashboard</a>
          </li>
        {% endif %}
        
      </ul>

        {% if user.is_authenticated %}
        
          <li class="nav-item" style="list-style: none;">
            <a class="nav-link disabled" href="#">  Welcome {{ user.username | title }}  </a>
          </li>


          <li class="nav-item " style="list-style: none;">
          <a href="{% url 'market:cart'%}" class="cart position-relative d-inline-flex" aria-label="View your shopping cart">
          <i class="fas fa fa-shopping-cart fa-lg"></i>
          <span class="cart-basket d-flex align-items-center justify-content-center">
            0
          </span>
        </a>
          </li>
          <li class="nav-item " style="list-style: none;">..</li>
        {% else %}
          <li class="nav-item" style="list-style: none;">
            <a class="nav-link" href="{% url 'user:login'%}"> Sign In </a>
          </li>
        {% endif %}


      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

    </div>
  </div>
</nav>
</main>

user/templates/user/dashboard.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %}{{ user.username|title }}-Dashboard{% endblock title %}
  </title>
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/bootstrap/dashboard.css' %}" rel="stylesheet">
  <style>
  #completed-orders{
    background-color:rgb(104, 167, 104);
  }

  #pending-orders{
    background-color:darkseagreen;
    
}

  #total-orders{
    background-color: grey;
  }

</style>

</head>
<body>
  <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="{% url 'market:home' %}" style="color:goldenrod ;"><h4> Nicks Shorts</h4></a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
        <div class="navbar-nav">
          <div class="nav-item text-nowrap">
            <a class="nav-link px-3" href="{% url 'user:logout' %}">Sign out</a>
          </div>
        </div>
      </header>

      <div class="container-fluid">
        <div class="row">
          <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="position-sticky pt-3">
              <ul class="nav flex-column">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="#">
                    <span data-feather="home"></span>
                    Profile
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <span data-feather="file"></span>
                    Orders
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <span data-feather="shopping-cart"></span>
                    Recent
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'market:cart' %}">
                    <span data-feather="users"></span>
                    My Cart
                  </a>
                </li>
               
              <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                <span>Support</span>
                <a class="link-secondary" href="#" aria-label="Add a new report">
                  <span data-feather="plus-circle"></span>
                </a>
              </h6>
              <ul class="nav flex-column mb-2">
                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <span data-feather="file-text"></span>
                    Feedback
                  </a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="#">
                    <span data-feather="file-text"></span>
                    Buy us Coffee
                  </a>
                </li>
                
                
              </ul>
            </div>
          </nav>

          <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
             {% block dashboard_center %}
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
              <h1 class="h2"> Welcome {{ user.username|title }}</h1>

              <div class="btn-toolbar mb-2 mb-md-0">
                <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
                  <span data-feather="calendar"></span>
                  This Week
                </button>
              </div>
            </div>
            <!-- TODO: Add a Chart later
              <canvas class="my-4 w-100" id="myChart" width="900" height="50"></canvas>
            -->
      <div class="row">
        <div class="col" id="total-orders">
          <h3>Total: <strong>{% comment %}{{total}}{% endcomment %}</strong> </h3>
        </div>

        <div class="col" id="completed-orders">
          <h4>Completed: <strong>{% comment %}{{delivered}}{% endcomment %}</strong> </h4>
        </div>

        <div class="col" id="pending-orders">
          <h4>Pending: {% comment %}{{pending}}{% endcomment %} </h4>
        </div>
      </div>

      <hr>
     
            <h2>Recent</h2>
            <div class="table-responsive">
              <table class="table table-striped table-sm">
                <thead>
                  <tr>
                    <th scope="col"></th>
                    <th scope="col">Name</th>
                    <th scope="col">Price</th>
                    <th scope="col">Order Number</th>
                    <th scope="col"></th>
                    <th scope="col">Status</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>1</td>
                    <td>khaki Shorts</td>
                    <td>NGN 5,000</td>
                    <td>44534</td>
                    <td>4pm Yesterday</td>
                    <td>Pending</td>
                  </tr>
                </tbody>
              </table>
            </div>
        {% endblock dashboard_center %}
          </main>
        </div>
      </div>
</body>
<script src="{% static 'js/bootstrap/bootstrap.bundle.min.js' %}"></script>
</html>

user/templates/user/login.html
{% load static%}

<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css'%}">
  <link rel="stylesheet" href="{% static 'css/custom/login_style.css'%}">
</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
            {% csrf_token %}
						<div class="input-group mb-3">
							<input type="text" name="username" id="username">
						</div>

						<div class="input-group mb-2">
							<input type="password" name="password" id="password">
						</div>
              {% for msg in messages%}
                <p style="text-align: center;">{{ msg }}</p>
              {% endfor %}
            <div class="d-flex justify-content-center mt-3 login_container">
              <input onclick="validateForm()" class="btn login_btn" type="submit" value="Login">
            </div>
					</form>
				</div>
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						New Here? <a href="{% url 'user:register' %}" class="ml-2">Register</a>
					</div>
				</div>
			</div>
		</div>
	</div>

  <script src="{% static 'js/validate_login.js' %}"></script>  

	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Enter password...';

		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>